package main

import (
	"context"
	"flag"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"
	"web-microservice-starter/src/model"
	"web-microservice-starter/utils/database"
	applogger "web-microservice-starter/utils/logging"

	"github.com/rs/zerolog"

	"github.com/gin-contrib/logger"
	"github.com/gin-gonic/gin"
	"github.com/spf13/viper"
)

/*
**********************
Do not edit this file*
**********************
*/

// Create once per go file and re use log
var log *zerolog.Logger = applogger.GetInstance()
var configFilePath *string

func main() {
	configFilePath = flag.String("config-path", "conf/", "conf/")
	flag.Parse()

	loadConfig()

	gin.DisableConsoleColor()
	r := gin.New()
	setupLogger(r)
	setupRoutes(r)
	setupDatabase()
	startServer(r)
}

// loadConfig - Load the config parameters
func loadConfig() {
	viper.SetConfigName("app")
	viper.SetConfigType("yaml")
	viper.AddConfigPath(*configFilePath)
	if err := viper.ReadInConfig(); err != nil {
		if readErr, ok := err.(viper.ConfigFileNotFoundError); ok {
			log.Panic().Msgf("No config file found at %s\n", *configFilePath)
		} else {
			log.Panic().Msgf("Error reading config file: %s\n", readErr)
		}
	}
}

// setupDatabase - Set up database
func setupDatabase() {
	database.GetInstance()
	model.Migrate()
}

// startServer - Start server
func startServer(r *gin.Engine) {
	srv := &http.Server{
		Addr:    viper.GetString("server.port"),
		Handler: r,
	}

	go func() {
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatal().Msgf("Listen: %s\n", err)
		}
	}()

	// Wait for interrupt signal to gracefully shutdown the server with
	// a timeout of 5 seconds.
	quit := make(chan os.Signal)
	// kill (no param) default send syscall.SIGTERM
	// kill -2 is syscall.SIGINT
	// kill -9 is syscall.SIGKILL but can't be catch, so don't need add it
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Info().Msg("Shutting down server...\n")

	// The context is used to inform the server it has 5 seconds to finish
	// the request it is currently handling
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := srv.Shutdown(ctx); err != nil {
		log.Fatal().Msgf("Server forced to shutdown: %s\n", err)
	}

	log.Info().Msg("Server exiting\n")

}

// setupLogger - Configure logging for the server
func setupLogger(r *gin.Engine) {
	// Configure logger
	zlog := applogger.GetInstance()
	r.Use(logger.SetLogger(logger.Config{
		Logger: zlog,
		UTC:    true,
	}))
}
